import test from 'node:test';
import assert from 'node:assert';
import { buildApp } from '../app.js';

test('GET /health responds with { ok: true }', async () => {
  const app = await buildApp();

  const response = await app.inject({
    method: 'GET',
    url: '/health'
  });

  assert.strictEqual(response.statusCode, 200);

  assert.deepStrictEqual(response.json(), { ok: true });

  await app.close();
});

test('GET / responds with the HTML page', async () => {
  const app = await buildApp();

  const response = await app.inject({
    method: 'GET',
    url: '/'
  });

  assert.strictEqual(response.statusCode, 200);
  assert.match(response.headers['content-type'], /text\/html/);

  const body = response.body;
  assert.ok(body.includes('QuoteBoard'), 'Page should contain the QuoteBoard title');
  assert.ok(body.includes('<form'), 'Page should contain the submission form');

  await app.close();
});

test('POST /quotes redirects to / on successful creation', async () => {
  const app = await buildApp();

  const response = await app.inject({
    method: 'POST',
    url: '/quotes',
    payload: {
      author: 'Test Runner',
      text: 'This quote was generated by an automated test.'
    }
  });

  assert.strictEqual(response.statusCode, 302);
  assert.strictEqual(response.headers.location, '/');

  await app.close();
});

test('POST /quotes rejects empty text and redirects back to /', async () => {
  const app = await buildApp();

  const response = await app.inject({
    method: 'POST',
    url: '/quotes',
    payload: {
      author: 'Sneaky User',
      text: '   '
    }
  });
  
  assert.strictEqual(response.statusCode, 302);
  assert.strictEqual(response.headers.location, '/');

  await app.close();
});